### ISSUE TITLE
Cookies reviews

### ISSUE THREAD

**Issue by defong** [DFE-Digital/manage-courses-frontend#18]
These are needs to be reviewed

https://github.com/DFE-Digital/manage-courses-frontend/blob/c2a025b6f28431b17dc96e082f7e414c03baadbf/app/views/pages/cookies.html.erb#L106

https://github.com/DFE-Digital/manage-courses-frontend/blob/c2a025b6f28431b17dc96e082f7e414c03baadbf/app/views/pages/cookies.html.erb#L111

**Comment by tvararu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Track and expose which users have seen the transition screen](https://trello.com/c/KaeVi9jt/1251-track-and-expose-which-users-have-seen-the-transition-screen)
